// Generated by LiveScript 1.5.0
(function(){
  var PredictSheetRows;
  PredictSheetRows = (function(){
    PredictSheetRows.displayName = 'PredictSheetRows';
    var prototype = PredictSheetRows.prototype, constructor = PredictSheetRows;
    function PredictSheetRows(){
      this.fea_row = new FeatureSheetRow;
    }
    PredictSheetRows.prototype.GenerateFromSheetFile = function(sheetdict){
      var strout, i$, own$ = {}.hasOwnProperty;
      strout = '';
      for (i$ in sheetdict) if (own$.call(sheetdict, i$)) {
        (fn$.call(this, i$, sheetdict[i$]));
      }
      return strout;
      function fn$(sheetname, mysheet){
        var feadict, i$, own$ = {}.hasOwnProperty;
        feadict = this.fea_row.GenerateSingularFeatureCrf(mysheet, sheetname);
        for (i$ in feadict) if (own$.call(feadict, i$)) {
          (fn$.call(this, i$, feadict[i$]));
        }
        function fn$(row, feavec){
          var numrow;
          numrow = row - 1;
          strout += numrow + ' ';
          feavec.forEach(function(item){
            if (item === true) {
              return strout += '1 ';
            } else {
              return strout += '0 ';
            }
          });
          strout += 'Title\n';
        }
      }
    };
    return PredictSheetRows;
  }());
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = Table;
  }
}).call(this);
